### ISSUE TITLE
당선 횟수 데이터 타입 관련

### ISSUE THREAD

**Issue by ksknote** [WIP-Who-Is-the-Pinocchio/frontend#17]
현재 당선 횟수 필드의 값이 초선, 재선, 3선 등 문자열 형식으로 되어있습니다.
추후 데이터 처리를 위해서 number로 통일하는 게 어떨까요?

**Comment by alsrlqor1007** [comment]
좋습니다! DB에서도 동일하게 정수형으로 관리하겠습니다.
