### ISSUE TITLE
국회의원 데이터 구조 개선 제안

### ISSUE THREAD

**Issue by ksknote** [WIP-Who-Is-the-Pinocchio/frontend#19]
데이터 구조와 타입과 관련하여 고민하다가 이슈에 남겨봅니다.
현재 국회의원 데이터를 폼을 통해 신규 업로드하는 페이지를 구현 중인데요.
기존 데이터 필드 그대로 적용하면 관리자의 입력값을 통제하기가 어렵고, 추후 관리하기 어려운 부분이 있을 것 같습니다.

제가 생각해본 데이터 형태를 공유하고자합니다. 고려한 기준은 아래와 같습니다.
- 신규 입력값에 대한 통제가 가능할 것
- 지역별, 완료현황별, 당선순 등 정렬기능을 위한 연산이 용이할 것

1. 지역구, 세부지역구, 분구 필드 분리
ex) 경기, 안양시 동안구, 갑

3. 상임위원회외 추가 상임위원회 필드 분리 
국회의원은 기본적으로 하나의 상임위원회의 위원이 됩니다. 그 외 의회운영위와 특별위원회의 위원을 겸직할 수 있다고 합니다. 따라서 기본적으로 속한 상임위원회와, 겸직인 경우의 추가 위원회 필드를 분리하면 좋을 것 같습니다. 

4. 당선 횟수는 초선, 재선 등의 문자열 대신 number타입으로 관리

5. 공약이행현황 등의 테이블 데이터는 이중 객체로 관리

6. 공약이행현황 등의 테이블 데이터는 값(number)과 비고 필드를 분리

7.  성격내용별완료현황 테이블에서 완료/전체 필드를 분리 

```
interface InputTypes {
  프로필: string;
  이름: string;
  지역구: string;
  세부지역구: string;
  분구: string;
  소속정당: string;
  당선횟수: number;
  상임위원회: string;
  추가상임위원회: string[];
  공약이행현황: {
    총공약수: {
      value: number;
      notes: string;
    };
    완료: {
      value: number;
      notes: string;
    };
    추진중: {
      value: number;
      notes: string;
    };
    보류: {
      value: number;
      notes: string;
    };
    폐기: {
      value: number;
      notes: string;
    };
    기타: {
      value: number;
      notes: string;
    };
  };
  성격내용별완료현황: {
    국정공약: { done: number; total: number; notes: string };
    지역공약: { done: number; total: number; notes: string };
    입법공약: { done: number; total: number; notes: string };
    재정공약: { done: number; total: number; notes: string };
    임기내: { done: number; total: number; notes: string };
    임기후: { done: number; total: number; notes: string };
    지속사업: { done: number; total: number; notes: string };
    신규사업: { done: number; total: number; notes: string };
  };
  입법현황: {
    필요입법공약총수: {
      value: number;
      notes: string;
    };
    입법의결완료공약총수: {
      value: number;
      notes: string;
    };
  };
  재정현황: {
    필요재정총액: {
      value: number;
      notes: string;
    };
    확보재정총액: {
      value: number;
      notes: string;
    };
    집행재정총액: {
      value: number;
      notes: string;
    };
  };
}
```

좋은 의견 있으시면 댓글 남겨주세요 😺

**Comment by alsrlqor1007** [comment]
와 수요일에 하나하나 얘기 나눠봐야 했던 내용들인데 미리 너무 잘 정리해주셔서 감사합니다!👍 

이대로 사용해도 괜찮아보이기도 하고, 아래와 같은 생각을 올려봅니다.

1. 상임위원회: string;
  추가상임위원회: string[];
이 두 가지를 바로 "상임위원회: string[]"으로 사용해도 괜찮아보입니다. 혹시 국회의원마다 추가상임위원회가 없을 가능성이 훨씬 크다면 nullable 요소를 줄일 수 있기도 한 것 같습니다.

2. 각 국회의원실에서 올리는 자료에 숫자 입력 값으로 "미제출"이나 기타 문자열처럼 예외들이 많은데, 숫자가 아니라면 어차피 정렬은 못하기 떄문에 저희 데이터상 null 값으로 모두 통일하고 note와 같은 부분을 최소화 하는 방향도 제안해봅니다! 정상적인 값을 입력하지 못한 사유가 필수적이라면, 또는 저희가 세부 창에는 보여줘야 한다면 notes 키는 살려야하기도 하니까 논의해보면 좋을듯합니다!

3. interface나 객체 등의 키는 추후 발생할 수 있는 인코딩 또는 기타 호환성 이슈로 한글은 지양하는 것으로 알고 있는데 이 부분은 문규님이랑 얘기해보시고 영문으로 관리해야 할 수도 있을 것 같습니다.

4. 추후 확장성을 위해 몇대 국회의원 데이터인지도 있으면 좋을듯 합니다!

마지막으로 이거는 제가 아직 정하지 못해서 드리는 질문인데,
지역구, 세부지역구, 분구 필드 분리
ex) 경기, 안양시 동안구, 갑
만약에 특별시, 광역시라면 지역구/세부지역구 분류가 어떻게 하는게 좋을지 미정입니다. 예를 들어, 서울이라면 지역구에 서울특별시여야 할수도 있는데 안양시는 세부지역구에 들어가게 되고, 이런 점이 아직 미정이라 다들 차차 의견 주시면 감사하겠습니다.

**Comment by uniqueeest** [comment]
되게 깔끔하게 정리가 잘 되었네요👍
1. 지역구 관련해서 저는 아래와 같이 정리하면 어떨까 싶습니다.
 - 특별시/광역시 : 지역구에 특별시/광역시를 넣고 세부 지역구에 '구'를 넣으면 어떨까요? 
 ``` 
서울 / 은평구/ 을
경기 / 의정부시 / 갑
경기 / 안양시 동안구 / 갑
```

**Comment by ksknote** [comment]
> 와 수요일에 하나하나 얘기 나눠봐야 했던 내용들인데 미리 너무 잘 정리해주셔서 감사합니다!👍
> 
> 이대로 사용해도 괜찮아보이기도 하고, 아래와 같은 생각을 올려봅니다.
> 
> 1. 상임위원회: string;
>    추가상임위원회: string[];
>    이 두 가지를 바로 "상임위원회: string[]"으로 사용해도 괜찮아보입니다. 혹시 국회의원마다 추가상임위원회가 없을 가능성이 훨씬 크다면 nullable 요소를 줄일 수 있기도 한 것 같습니다.
> 2. 각 국회의원실에서 올리는 자료에 숫자 입력 값으로 "미제출"이나 기타 문자열처럼 예외들이 많은데, 숫자가 아니라면 어차피 정렬은 못하기 떄문에 저희 데이터상 null 값으로 모두 통일하고 note와 같은 부분을 최소화 하는 방향도 제안해봅니다! 정상적인 값을 입력하지 못한 사유가 필수적이라면, 또는 저희가 세부 창에는 보여줘야 한다면 notes 키는 살려야하기도 하니까 논의해보면 좋을듯합니다!
> 3. interface나 객체 등의 키는 추후 발생할 수 있는 인코딩 또는 기타 호환성 이슈로 한글은 지양하는 것으로 알고 있는데 이 부분은 문규님이랑 얘기해보시고 영문으로 관리해야 할 수도 있을 것 같습니다.
> 4. 추후 확장성을 위해 몇대 국회의원 데이터인지도 있으면 좋을듯 합니다!
> 
> 마지막으로 이거는 제가 아직 정하지 못해서 드리는 질문인데, 지역구, 세부지역구, 분구 필드 분리 ex) 경기, 안양시 동안구, 갑 만약에 특별시, 광역시라면 지역구/세부지역구 분류가 어떻게 하는게 좋을지 미정입니다. 예를 들어, 서울이라면 지역구에 서울특별시여야 할수도 있는데 안양시는 세부지역구에 들어가게 되고, 이런 점이 아직 미정이라 다들 차차 의견 주시면 감사하겠습니다.

1. 저희가 조사한 자료에는 모두 상임위원회라는 이름으로 들어가있었지만, 상임위원회와 상설특별위원회는 엄연히 다른 개념의 조직이더라구요. 하지만 저희가 위원회를 가지고 추가적인 서비스를 제공할 계획은 없으니 말씀 주신 것처럼 하나의 배열로 관리하는 것도 괜찮은 것 같습니다!
2. 너무나 동의하는 내용입니다!
3. 입법의결완료공약총수 변수명 만들다가 한글로 바꿔버렸는데 다시 고민해보겠습니다.. :)
4. 천재👍

지역구와 관련해서 윤재님이 말씀하신 내용과 의견이 비슷합니다.
- 변동 가능성이 없는 행정구역(특별시1, 광역시6, 도8, 특별자치시1, 특별자치도1) 
- 선거구 획정으로 인한 변동 가능성이 있는 세부 지역구
- 분구

이렇게 관리하는게 최선이 아닐까 싶은데, 그럼에도 매 선거구 획정 때마다 통폐합과 분리 통해 변경되면 세부 지역구는 일관되게 관리하기가 어려울 것입니다ㅜㅜ 고민되는 부분이네요.
